options:
  lineNumbers: true
  spellcheck: false
  imagePath: /res/imgs/posts/
  overwriteImages: true
  askImageFilename: true
editor:
  lineNumbers: true
  inputStyle: contenteditable
  spellcheck: false
